services:
  arithmetic-service:
    image: arithmetic-service
    build:
      context: ../arithmetic-service
      dockerfile: Dockerfile
    container_name: arithmetic-service
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    restart: "no"
  
  azure-storage:
    image: azure-storage
    build:
      context: ../azure-storage-service
      dockerfile: Dockerfile
    container_name: azure_storage
    ports:
      - "4001:3000"
    environment:
      - PORT=3000
      - STORAGE_ACCOUNT_NAME=practicumsavi
      - STORAGE_ACCESS_KEY=
    restart: "no"

  history-database:
    image: postgres:alpine 
    container_name: history-database 
    ports: 
      - "4008:5432"
    environment:
       POSTGRES_PASSWORD: password
       POSTGRES_DB: history
